### ISSUE TITLE
GalleryFinal.captureMedia设置maxDuration 无效

### ISSUE THREAD

**Issue by aer874475222** [xushihai/MediaPicker#7]
protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.initUi();
        this.destnationPath = this.getIntent().getStringExtra("destnationPath");
        this.maxDuration = this.getIntent().getIntExtra("maxDuration", 10000);
    }
这句maxDuration 应该调到 this.initUi();的上面，否则无效

**Comment by xushihai** [comment]
已修复
