### ISSUE TITLE
拍摄的时候添加拍摄类型， TYPE_IMAGE = 1;//图片类型   TYPE_VIDEO = 2;//视频类型   TYPE_ALL = 3;//所有类型就完美了

### ISSUE THREAD

**Issue by MaZhanBiao** [xushihai/MediaPicker#8]
代码没怎么看简单修改了下不知道有没有问题，看到后还请修正下，期待越来越好
  rlStart.setOnTouchListener (new View.OnTouchListener () {
            @Override
            public boolean onTouch (View v, MotionEvent event) {
                Log.e ("拍摄", event.getAction () + "");
                switch (event.getAction ()) {
                    case MotionEvent.ACTION_DOWN:
                        start = System.currentTimeMillis ();
                        **if (mTakeType != GalleryFinal.TYPE_IMAGE)
                            handler.postDelayed (captureVideo, 300);**
                        break;
                    case MotionEvent.ACTION_CANCEL:
                    case MotionEvent.ACTION_UP:
                        **if (mTakeType != GalleryFinal.TYPE_IMAGE)
                            handler.removeCallbacks (captureVideo);**
                        if (mMediaRecorder == null) {
                            break;
                        }
                        long gap = System.currentTimeMillis () - start - 500;
                        int delay = gap > 1500 ? 0 : 1500;
                        countDownHandler.stop ();
                        recover ();
                        new Handler ().postDelayed (new Runnable () {
                            @Override
                            public void run () {
                                if (mMediaRecorder != null) {
                                    stopRecord ();
                                }
                            }
                        }, delay);
                        break;
                }
                return (System.currentTimeMillis () - start) > 500;
            }
        });

**Comment by xushihai** [comment]
已修改，谢谢你的鼓励
